"""create bundle model

Revision ID: 26f42331a031
Revises: 
Create Date: 2018-06-11 01:49:54.860331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f42331a031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_uuid', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=False),
    sa.Column('sensor_reading_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_device_uuid'), 'bundle', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_bundle_sensor_reading_time'), 'bundle', ['sensor_reading_time'], unique=False)
    op.create_index(op.f('ix_bundle_sensor_type'), 'bundle', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_bundle_sensor_value'), 'bundle', ['sensor_value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundle_sensor_value'), table_name='bundle')
    op.drop_index(op.f('ix_bundle_sensor_type'), table_name='bundle')
    op.drop_index(op.f('ix_bundle_sensor_reading_time'), table_name='bundle')
    op.drop_index(op.f('ix_bundle_device_uuid'), table_name='bundle')
    op.drop_table('bundle')
    # ### end Alembic commands ###
